# Generated by Django 5.1.7 on 2025-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
