# Generated by Django 5.1.7 on 2025-04-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
