# Generated by Django 5.1.7 on 2025-04-06 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_fee_payment_method'),
        ('students', '0006_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='total_fees',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='fee',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feeitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='students.student')),
            ],
        ),
    ]
