# Generated by Django 5.1.7 on 2025-04-06 00:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feeitem_rename_total_fees_fee_amount_and_more'),
        ('students', '0006_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeeitem',
            name='fee_item',
        ),
        migrations.RemoveField(
            model_name='studentfeeitem',
            name='student',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='name',
        ),
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.DeleteModel(
            name='FeeItem',
        ),
        migrations.DeleteModel(
            name='StudentFeeItem',
        ),
    ]
