# Generated by Django 5.1.7 on 2025-04-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_studentfeeitem_fee_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
