# Generated by Django 5.1.7 on 2025-04-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_remove_payment_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Paid', max_length=20),
        ),
    ]
